### ISSUE TITLE
移动端开发之rem

### ISSUE THREAD

**Issue by Guohjia** [Guohjia/ShenZhen-School#2]
## 首先，先认识几个基本单位
*  px:是测量的绝对单位,根据浏览器窗口的宽度不会缩放,显示器(手机屏幕)上最小的物理显示单元，在操作系统的调度下，每一个设备像素都有自己的颜色值和亮度值。
* em:不是绝对单位 - 它是相对于当前选择(父容器或者当前环境)的字体大小的单位。
* rem:（相对于根元素(html)字体大小）

##  解决方案:
1.响应式(媒体查询):大型企业不采用，因为工作大，维护性难，所以只是用于中小心企业或者个人博客与简历，就不必为(pc/移动端)写两套代码

2.viewport缩放:可以320宽度(iphone5)为基准，进行缩放，这个方法简单粗暴，又高效(如天猫web app)，但安卓浏览器版本需要4.4及以上,如果不考虑这部分用户，可以用vw

3.如果想考虑安卓4.4以下用户，设置rem等比例适配所有屏幕，兼容性比vw更好，不过稍复杂一些

#### 1.禁止980px的样式缩放 
```js
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
```
#### 2.设置html{font-size:页面宽度/10px}
* 1.媒体查询，统计用户屏幕，部分适配，如
```css
     @media (min-device-width : 375px) and (max-device-width : 667px) and (-webkit-min-device-pixel-
     ratio : 2){
      html{font-size: 37.5px;}
     }
```
* 2.js实现(匹配所有屏幕)
```js
        var pageWidth=document.documentElement.clientWidth; 
        var content='html{font-size:'+pageWidth/10+'px}'  
          //10rem=页面宽度   320px=10rem,1rem=32px ;
          //除以10是为了便于计算，也可以不除，但不能除以100，否则会导致字体大小设置过小
        var style=document.createElement('style')
        style.innerHTML=content
        document.head.appendChild(style) 
```

#### 3.所有单位设置rem,所有长度都以页面宽度为基准;   

计算方法:可采用scss计算(以设计稿为基准,这里是iphone6)
```css
@function px2rem($px){
    $rem : 37.5px;
    @return ($px/$rem) + rem;
})
```
这样我们写具体值的时候(避免了繁琐的计算)：
```css
height:90px;
width:90px
```
可以写成:
```css
height: px2rem(90px);
width: px2rem(90px);;
```

## 1px问题：主要由于不同屏幕不同的dpr(device pixel ratio)所造成
* 在普通屏幕下，1个css像素 对应 1个物理像素(1:1)。
* 在retina 屏幕下，1个css像素对应 4个物理像素(1:4)(ratina=2);  
* 上述情况导致图片就近取色，失去清晰度;border,字体大小不能保证始终处于设备的1px状态

#### 解决方案:使不同dpr,css中设置的1px始终对应设备的1个物理像素
* 1.获取像素比 dpr=window.devicePixelRatio
* 2.设置scale=1/dpr
        如2dpr下面，1个css像素对应 4个物理像素，因此字体大小，border如果要保持css1px就是对应设备1px不变，图片要设置固定的px不失真，可以设置scale:1/2
* 3.让原来的rem变为rem*dpr
因为视觉上的1px由于dpr设置整体缩小了，因此设置rem的部分需要放大至原来的大小，如果是2dpr，那么我们直接把rem扩大两倍,本来1个rem应该是37.5px，现在变成要75px,这样才能实现预期中的所有内容等比缩放的效果,之前的scss变成:
```css
@function px2rem($px){
    $rem : 75px;  //iphone6的标准基准值由于其dpr为2,原来的37.5px变成2倍为75px
    @return ($px/$rem) + rem; 
}
```
